# Generated by Django 4.1.3 on 2022-12-07 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_attendance_assign_attendance_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='session',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
        migrations.AddField(
            model_name='attendance',
            name='assign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.assign'),
        ),
    ]
