# Generated by Django 4.1.3 on 2022-12-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_attendance_session_remove_attendance_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='assign',
        ),
        migrations.AddField(
            model_name='attendance',
            name='assign',
            field=models.ManyToManyField(null=True, to='main_app.assign'),
        ),
    ]
