# Generated by Django 4.1.3 on 2022-12-09 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_attendance_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportstudent',
            name='assign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.assign'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], max_length=2, null=True),
        ),
    ]
