# Generated by Django 4.1.3 on 2022-12-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_leavereportstudent_assign_alter_subject_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereportstudent',
            name='assign',
        ),
    ]
