# Generated by Django 4.1.3 on 2022-12-09 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_attendance_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='assign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.assign'),
        ),
    ]
