# Generated by Django 4.1.3 on 2022-12-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_attendance_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaff',
            name='date',
            field=models.DateField(max_length=60),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='date',
            field=models.DateField(max_length=60),
        ),
    ]
