# Generated by Django 4.1.3 on 2022-12-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_attendancereport_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='assign',
        ),
    ]
